// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHVD_Ab57ij3ZuEQkgbXObxibRAvIF1ns',
    appId: '1:146403492002:web:25716be97d095f512117fb',
    messagingSenderId: '146403492002',
    projectId: 'pregnancy-app-4fffb',
    authDomain: 'pregnancy-app-4fffb.firebaseapp.com',
    storageBucket: 'pregnancy-app-4fffb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8D5AuKOc3ayqF9nl6gV5vfzkVcdDH7L8',
    appId: '1:146403492002:android:6d0c8ba343bba6b32117fb',
    messagingSenderId: '146403492002',
    projectId: 'pregnancy-app-4fffb',
    storageBucket: 'pregnancy-app-4fffb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzyy7YBpO4a3R2k15dxA2nckG9KXutbUM',
    appId: '1:146403492002:ios:d14925939ac314762117fb',
    messagingSenderId: '146403492002',
    projectId: 'pregnancy-app-4fffb',
    storageBucket: 'pregnancy-app-4fffb.appspot.com',
    iosBundleId: 'com.example.pragnancyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzyy7YBpO4a3R2k15dxA2nckG9KXutbUM',
    appId: '1:146403492002:ios:d14925939ac314762117fb',
    messagingSenderId: '146403492002',
    projectId: 'pregnancy-app-4fffb',
    storageBucket: 'pregnancy-app-4fffb.appspot.com',
    iosBundleId: 'com.example.pragnancyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHVD_Ab57ij3ZuEQkgbXObxibRAvIF1ns',
    appId: '1:146403492002:web:5c6b1304a8bd46802117fb',
    messagingSenderId: '146403492002',
    projectId: 'pregnancy-app-4fffb',
    authDomain: 'pregnancy-app-4fffb.firebaseapp.com',
    storageBucket: 'pregnancy-app-4fffb.appspot.com',
  );
}
